#!/bin/sh
./pr.exe -i "../in/test1.txt" -o "../out/out1.txt" 
echo "Test1"
cat "../out/out1.txt"
./pr.exe -i "../in/test2.txt" -o "../out/out2.txt"
echo "Test2"
cat "../out/out2.txt"
./pr.exe -i "../in/test3.txt" -o "../out/out3.txt"
echo "Test3"
cat "../out/out3.txt"
./pr.exe -i "../in/test4.txt" -o "../out/out4.txt" 
echo "Test4"
cat "../out/out4.txt"
./pr.exe -i "../in/test5.txt" -o "../out/out5.txt" 
echo "Test5"
cat "../out/out5.txt"
./pr.exe -i "../in/test6.txt" -o "../out/out6.txt"
echo "Test6"
cat "../out/out6.txt"
./pr.exe -i "../in/test7.txt" -o "../out/out7.txt"
echo "Test7"
cat "../out/out7.txt"
./pr.exe -i "../in/test8.txt" -o "../out/out8.txt"
echo "Test8"
cat "../out/out8.txt"
./pr.exe -i "../in/test9.txt" -o "../out/out9.txt"
echo "Test9"
cat "../out/out9.txt"
./pr.exe -i "../in/test10.txt" -o "../out/out10.txt"
echo "Test10"
cat "../out/out10.txt"
./pr.exe -i "../in/test11.txt" -o "../out/out11.txt"
echo "Test11"
cat "../out/out11.txt"
./pr.exe -o "../out/out12.txt" -g
echo "Test12"
cat "../out/out12.txt"